app/urls.py
from django.urls import path
from . import views
app_name = 'boards'

urlpatterns = [
    path('', views.boards_list, name='home'),
    
    # path('about/', views.about, name='about'),
    path('boards/<int:board_id>/', views.board_topics, name='board_topics'),
    path('boards/<int:board_id>/new/', views.new_topic, name='new_topic'),
    # path('boards/<int:board_id>/topics/<int:topic_id>/', views.topic_posts, name='topic_posts'),
    # path('boards/<int:board_id>/topics/<int:topic_id>/reply/', views.reply_topic, name='reply_topic'),
    # path('boards/<int:board_id>/topics/<int:topic_id>/posts/<int:post_id>/edit/', views.PostUpdateView.as_view(), name='edit_post'),
]

frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
import requests
import json
# Create your views here.

def boards_list(request):
    backend_url = 'http://127.0.0.1:8000/'
    headers = {'content-type':'application/json'}
    response = requests.get(backend_url, headers=headers)
   
    boards = response.json()
    return render(request, 'home.html', {'boards':boards})


def board_topics(request, board_id):
    backend_url = f'http://127.0.0.1:8000/boards/' + str(board_id) 
    headers = {'content-type': 'application/json'}
    response = requests.get(backend_url, headers=headers)
    response_data = response.json()

    response_board = requests.get('http://127.0.0.1:8000/board_detail/'+str(board_id), headers=headers)
    board_details = response_board.json()
    return render(request, 'topics.html', {'board':board_details, 'topics':response_data})
    # response_data = {'board': response_data['results'], 'topics':response_data.get('topics')}
    # return render(request, 'topics.html', response_data) ==========================================> if we use functions


def new_topic(request, board_id):
    headers = {'content-type': 'application/json'}
    response_board = requests.get('http://127.0.0.1:8000/board_detail/'+str(board_id), headers=headers)

    board_details = response_board.json()
    if request.method == 'POST':
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        created_by = 1
        data = json.dumps({'subject':subject, 'message':message, 'created_by':created_by, 'board':board_id})
        response_board = requests.post('http://127.0.0.1:8000/boards/'+str(board_id), headers=headers, data=data)
        add_topic_res = response_board.json()
        return redirect('boards:board_topics', board_id =board_id )
        
    return render(request, 'new_topic.html', {'board':board_details})

app/templates/aaaaaaa.html
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    {% block stylesheet %}{% endblock %}

</head>
<body>
{%block body%}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainMenu">
      {%if user.is_authenticated%}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Welcome  {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="{%url 'my_account'%}">My account</a>
            <a class="dropdown-item" href="{%url 'password_change'%}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        </li>
      </ul>
        {%else%}
        <form class="form-inline ml-auto">
        <a href="{%url 'login'%}" class="btn btn-outline-secondary">login</a>
        <a href="{%url 'signup'%}" class="btn btn-primary ml-2">Signup</a>
        </form>
            {%endif%}

    </div>
  </div>
</nav>
<div class="container">
<ol class="breadcrumb my-4">
    {% block breadcrumb %}
    {% endblock %}
</ol>

    {% block content %}
    {% endblock %}

</div>
{%endblock body%}
<script src="{%static 'js/jquery-3.4.1.min.js'%}"></script>
<script src="{%static 'js/popper.min.js'%}"></script>
<script src="{%static 'js/bootstrap.min.js'%}"></script>

</body>
</html>

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" >  

    <style>
        .table {
            width: 100%;
            border-collapse: collapse;
        }
        .table thead {
            background-color: #343a40;
            color: #fff;
        }
        .table th,
        .table td {
            border: none;
            border-bottom: 1px solid #dee2e6;
        }
        .table th {
            text-align: left;
        }
        .board-title {
            background-color: #f8f9fa;
            padding: 10px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            margin-bottom: 20px;
            font-weight: bold;
        }
        .board-name {
            font-size: 20px;
        }
        .board-description {
            color: #6c757d;
        }
        body {
            margin: 0; /* Reset default margin */
            padding: 0; /* Reset default padding */
        }
        .container {
            margin-left: 20px; /* Move the blocks to the left */
        }
    </style>
</head>
<body>
 
    

    {% block content %}
    {% endblock content %}

    {% block body %}
    {% endblock body %}

    <!-- JS here -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script> 
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  
      
</body>
</html>

app/templates/change_password.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load bootstrap4 %}

{% block title %}
    Change Password
{% endblock %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name">Change Password</div>
        </div>

        <form method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <!-- {% include 'includes/form.html' %} -->
            <div class="form-group">
                <button type="submit" class="boxed-btn3 w-100">Change Password</button>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/change_password_done.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load bootstrap4 %}

{% block title %}
    Change Password Successful
{% endblock %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name">
                <a href="{% url 'change_password' %}">Change Password</a>
            </div>
        </div>

        <div class="alert alert-success" role="alert">
            Your password has been successfully changed :)
        </div>
        <a href="{% url 'boards:home' %}">Return To Home</a>
    </div>
{% endblock %}

app/templates/edit_post.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load bootstrap4 %}

{% block title %}
    Edit Post
{% endblock %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name"><a href="{% url 'boards:home' %}">Boards</a> / <a href="{% url 'boards:board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a> / Edit Post</div>
        </div>

        <form method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <!-- {% include 'includes/form.html' %} -->
            <div class="form-group">
                <button type="submit" class="boxed-btn3 w-10"> Save Changes</button>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Board
{% endblock %}

{% block content %}
<div class="board-title">
    <div class="board-name">Board</div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
        </tr>
    </thead>
    <tbody>
        {% for board in boards %}
        <tr>
            <td>
                <div class="board-name"><a href="{% url 'boards:board_topics' board.id %}">{{board.name}}</a></div>
                <div class="board-description">{{board.description}}</div>
            </td>
            <td>{{board.get_posts_count}}</td>
            <td>{{board.topics.count}}</td>
            <td>
                {% with post=board.get_last_post %}
                {% if post %}
                by {{post.created_by.username}} at {{post.created_dt}}
                {% else %}
                <small>No Posts</small>
                {% endif %}
                {% endwith %}
            </td>
        </tr>
        <tr style="height: 10px;"></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/includes/form.html
{% load bootstrap4 %}
{% bootstrap_form form %}

{% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

app/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class='container'>
    <h1>Login</h1>
    <form method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <input type="hidden" name='next' value='{{next}}'>
        {% bootstrap_form form %}
        {% if form.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <!-- {% include 'includes/form.html' %} -->
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Login</button>
        </div>
    </form>
    <p class="text-center">Create new account <a href="{% url 'login' %}" class="btn btn-primary">Signup</a></p>
</div>

{% endblock content %}

app/templates/my_account.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    My account
{% endblock %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name">My account</div>
        </div>
        <form method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="form-group">
                <button type="submit" class="boxed-btn3 w-10">Save Changes</button>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/new_topic.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
    Create New Topic
{% endblock %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name"><a href="{% url 'boards:home' %}">Boards</a> / <a href="{% url 'boards:board_topics' board.id %}">{{ board.name }}</a> / New Topic</div>
        </div>

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="subject">Subject:</label>
                <input type="text" class="form-control" id="subject" name="subject">
            </div>
            <div class="form-group">
                <label for="message">Message:</label>
                <textarea class="form-control" id="message" name="message"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        
    </div>
{% endblock %}

app/templates/reply_topic.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ topic.subject }}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name">
                <a href="{% url 'boards:home' %}">Boards</a> /
                <a href="{% url 'boards:board_topics' topic.board.id %}">{{ topic.board.name }}</a> /
                {{ topic.subject }} / Post reply
            </div>
        </div>
    </div>
{% endblock content %}

{% block body %}
<form action="" method='POST' class='mb-4' enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {%include 'includes/form.html' %}
    <div class="form-group">
        <button type="submit" class="btn btn-success">Reply the post</button>
    </div>
</form>

<div class="col-12">
    {% for post in topic.posts.all %}
        <div class="row" style="border: 1px solid #ccc; border-radius: 5px; padding: 10px; width: 62%;">
            <div class="col-2">
                <img src="{% static 'img/user.png' %}" alt="{{ post.created_by.username }}" style="width: 70%;">
            </div>
            <div class="col-10">
                <p>{{ post.created_by.username }}</p>
                <p>{{ post.message }}</p>
                <p>{{ post.created_dt }}</p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock body %}

app/templates/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class='container'>
    <h1>Signup</h1>
    <form method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% if form.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <!-- {% include 'includes/form.html' %} -->
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Create New User</button>
        </div>
    </form>
    <p class="text-center">Already have an account? <a href="{% url 'login' %}" class="btn btn-primary">Login</a></p>

</div>

{% endblock content %}

app/templates/topic_posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ topic.subject }}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name">
                <a href="{% url 'boards:home' %}">Boards</a> /
                <a href="{% url 'boards:board_topics' topic.board.id %}">{{ topic.board.name }}</a> /
                {{ topic.subject }}
            </div>
        </div>
    </div>
{% endblock content %}

{% block body %}
    <div class="container">
        <div class="mb-4">
            <a href="{% url 'boards:reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary">Replay</a>
        </div>

        <div class="row" >
            <div class="col-12">
                {% for post in topic.posts.all %}
                    <div class="row" style="border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
                        <div class="col-2">
                            <img src="{% static 'img/user.png' %}" alt="{{ post.created_by.username }}" style="width: 70%;">
                        </div>
                        <div class="col-10">
                            <p>{{ post.created_by.username }}</p>
                            <p>{{ post.message }}</p>
                            <p>{{ post.created_dt }}</p>
                            {% if post.created_by == user %}
                                <a href="{% url 'boards:edit_post' post.topic.board.pk post.topic.id post.pk %}" class="btn btn-primary">Edit</a>
                            {% endif %}
                        </div>
                                                
                    </div>
                    <br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

app/templates/topics.html
{% extends 'base.html' %}

{% block title %}
    {{ board.name }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="board-title">
            <div class="board-name"><a href="{% url 'boards:home' %}">Boards</a> / {{ board.name }}</div>
        </div>
        <a href="{% url 'boards:new_topic' board.id %}" class="btn btn-primary">New Topic</a>
        

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Topics</th>
                    <th>Created by</th>
                    <th>Posts</th>
                    <th>Views</th>
                    <th>Created dt</th>
                </tr>
            </thead>
            <tbody>
                {% for topic in topics %}
                <tr>
                    <td><a href="">{{ topic.subject }}</a></td>
                    <td>{{ topic.creater_name}}</td>
                    <td>{{topic.comments}}</td>
                    <td>{{topic.views}}</td>
                    <td>{{topic.created_dt}}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if topics.has_other_pages %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if topics.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in topics.paginator.page_range %}
        {% if topics.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if topics.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

    </div>
{% endblock %}